/**
 * Original menu — Kefyro ūsai (meniu-1.jpg, meniu-2.jpg)
 * Last synced: 2026-07-15
 */
import { PHOTOS } from "../media";

export type FoodSection =
  | "snacks"
  | "tortillas"
  | "salads"
  | "mains"
  | "soups"
  | "desserts";

export type DrinkSection =
  | "beerDraft"
  | "beerBottle"
  | "spirits"
  | "wine"
  | "cider"
  | "cocktails"
  | "shots"
  | "coffee"
  | "soft";

export interface ScrapedMenuItem {
  id: string;
  name: { lt: string; en: string };
  description: { lt: string; en: string };
  price: number;
  displayPrice?: { lt: string; en: string };
  image: string;
  vegan?: boolean;
  allergens?: string[];
  category: "food" | "cocktails" | "wineBeer" | "nonAlcoholic";
  section?: FoodSection | DrinkSection;
}

export const FOOD_SECTIONS: { key: FoodSection; label: { lt: string; en: string } }[] = [
  { key: "snacks", label: { lt: "Užkandžiai", en: "Appetizers" } },
  { key: "tortillas", label: { lt: "Tortilijos", en: "Tortillas" } },
  { key: "salads", label: { lt: "Salotos", en: "Salads" } },
  { key: "mains", label: { lt: "Pagrindiniai patiekalai", en: "Main courses" } },
  { key: "soups", label: { lt: "Sriubos", en: "Soups" } },
  { key: "desserts", label: { lt: "Desertai", en: "Desserts" } },
];

export const DRINK_SECTIONS: {
  key: DrinkSection;
  label: { lt: string; en: string };
  category: "cocktails" | "wineBeer" | "nonAlcoholic";
}[] = [
  { key: "beerDraft", label: { lt: "Pilstomas alus", en: "Draught beer" }, category: "wineBeer" },
  { key: "beerBottle", label: { lt: "Alus buteliuose", en: "Bottled beer" }, category: "wineBeer" },
  { key: "spirits", label: { lt: "Stiprieji gėrimai 40 ml", en: "Spirits 40 ml" }, category: "wineBeer" },
  { key: "wine", label: { lt: "Vynas", en: "Wine" }, category: "wineBeer" },
  { key: "cider", label: { lt: "Sidras", en: "Cider" }, category: "wineBeer" },
  { key: "cocktails", label: { lt: "Alkoholiniai kokteiliai", en: "Alcoholic cocktails" }, category: "cocktails" },
  { key: "shots", label: { lt: "Shotai (4 vnt.)", en: "Shots (4 pcs)" }, category: "cocktails" },
  { key: "coffee", label: { lt: "Kava ir arbata", en: "Coffee & tea" }, category: "nonAlcoholic" },
  { key: "soft", label: { lt: "Nealkoholiniai gėrimai", en: "Non-alcoholic drinks" }, category: "nonAlcoholic" },
];

export const MENU_PAGES = {
  food: PHOTOS.meniuFood,
  drinks: PHOTOS.meniuDrinks,
  note: { lt: "Užsakymai priimami prie baro", en: "Orders taken at the bar" },
};

export const SCRAPED_MENU: ScrapedMenuItem[] = [
  // —— Užkandžiai ——
  {
    id: "duona-parmezanas",
    name: { lt: "Kepta „Kefyro ūsų“ duonelė", en: "Kefyro ūsai garlic bread" },
    description: {
      lt: "Kepta česnakinė duonelė su parmezano sūriu ir pikantišku padažu",
      en: "Grilled garlic bread with parmesan and spicy sauce",
    },
    price: 7,
    image: PHOTOS.baras,
    category: "food",
    section: "snacks",
  },
  {
    id: "empanados",
    name: { lt: "Empanados", en: "Empanadas" },
    description: {
      lt: "Ispaniški pyragėliai su kumpiu ir sūriu",
      en: "Spanish pastries with ham and cheese",
    },
    price: 8,
    image: PHOTOS.baras2,
    category: "food",
    section: "snacks",
  },
  {
    id: "surio-kamuoliukai",
    name: { lt: "Sūrio kamuoliukai su jelapenais ir padažu", en: "Cheese balls with jalapeños" },
    description: { lt: "Traškūs sūrio kamuoliukai su jelapenais", en: "Crispy cheese balls with jalapeños" },
    price: 8,
    image: PHOTOS.baras,
    category: "food",
    section: "snacks",
  },
  {
    id: "kalmaru-ziedai",
    name: { lt: "Kalmarų žiedai su žolelėmis", en: "Calamari rings with herbs" },
    description: { lt: "Kalmarų žiedai su žolelių padažu", en: "Calamari rings with herb sauce" },
    price: 8,
    image: PHOTOS.baras3,
    category: "food",
    section: "snacks",
    allergens: ["shellfish"],
  },
  {
    id: "bulviu-traskuciai",
    name: { lt: "Naminiai bulvių traškučiai", en: "Homemade potato chips" },
    description: { lt: "Naminiai bulvių traškučiai su naminiu padažu", en: "Homemade potato chips with house sauce" },
    price: 7,
    image: PHOTOS.baras4,
    category: "food",
    section: "snacks",
  },
  {
    id: "svogunu-ziedai",
    name: { lt: "Svogūnų žiedai", en: "Onion rings" },
    description: { lt: "Traškūs svogūnų žiedai", en: "Crispy onion rings" },
    price: 7,
    image: PHOTOS.baras,
    category: "food",
    section: "snacks",
    vegan: true,
  },
  {
    id: "bulvytes",
    name: { lt: "Bulvytės", en: "French fries" },
    description: { lt: "Traškios bulvytės fri", en: "Crispy french fries" },
    price: 5,
    image: PHOTOS.baras5,
    category: "food",
    section: "snacks",
    vegan: true,
  },
  {
    id: "uzkandziu-rinkinys",
    name: { lt: "Užkandžių rinkinys", en: "Appetizer platter" },
    description: {
      lt: "Vištienos sparneliai, nachos traškučiai, kietasis sūris, kepta duonelė, alyvuogės, kalmarų ir svogūnų žiedai",
      en: "Chicken wings, nachos, hard cheese, garlic bread, olives, calamari and onion rings",
    },
    price: 25,
    image: PHOTOS.baras2,
    category: "food",
    section: "snacks",
  },
  // —— Tortilijos ——
  {
    id: "tortilija-vistiena",
    name: { lt: "Tortilija su traškia vištiena", en: "Tortilla with crispy chicken" },
    description: { lt: "Firminė tortilija su traškia vištiena ir šviežiomis daržovėmis", en: "Signature tortilla with crispy chicken and fresh vegetables" },
    price: 8,
    image: PHOTOS.tortilija,
    category: "food",
    section: "tortillas",
  },
  {
    id: "tortilija-kebabas",
    name: { lt: "Tortilija su vištienos kebabo mėsa", en: "Tortilla with chicken kebab" },
    description: { lt: "Firminė tortilija su vištienos kebabo mėsa", en: "Signature tortilla with chicken kebab meat" },
    price: 8,
    image: PHOTOS.tortilija,
    category: "food",
    section: "tortillas",
  },
  {
    id: "tortilija-falafel",
    name: { lt: "Vegetariška tortilija su falafeliais", en: "Vegetarian falafel tortilla" },
    description: { lt: "Tortilija su falafeliais ir šviežiomis daržovėmis", en: "Tortilla with falafel and fresh vegetables" },
    price: 8,
    image: PHOTOS.tortilija,
    category: "food",
    section: "tortillas",
    vegan: true,
  },
  {
    id: "tortilija-vegan",
    name: { lt: "Veganiška tortilija su falafeliais", en: "Vegan falafel tortilla" },
    description: { lt: "Veganiška tortilija su falafeliais ir daržovėmis", en: "Vegan tortilla with falafel and vegetables" },
    price: 8,
    image: PHOTOS.tortilija,
    category: "food",
    section: "tortillas",
    vegan: true,
  },
  // —— Salotos ——
  {
    id: "salotos-vistiena",
    name: { lt: "Salotos su traškia vištiena", en: "Salad with crispy chicken" },
    description: {
      lt: "Šviežios daržovės, salotų lapai, parmezano sūris, žolelių padažas, marinuoti svogūnai",
      en: "Fresh vegetables, lettuce, parmesan, herb dressing, pickled onions",
    },
    price: 10,
    image: PHOTOS.salotos,
    category: "food",
    section: "salads",
  },
  {
    id: "salotos-falafel",
    name: { lt: "Salotos su falafeliais", en: "Salad with falafel" },
    description: {
      lt: "Šviežios daržovės, salotų lapai, parmezano sūris, žolelių padažas, marinuoti svogūnai",
      en: "Fresh vegetables, lettuce, parmesan, herb dressing, pickled onions",
    },
    price: 10,
    image: PHOTOS.salotos,
    category: "food",
    section: "salads",
    vegan: true,
  },
  {
    id: "salotos-krevetes",
    name: { lt: "Salotos su krevetėmis", en: "Salad with shrimp" },
    description: {
      lt: "Šviežios daržovės, salotų lapai, parmezano sūris, žolelių padažas, marinuoti svogūnai",
      en: "Fresh vegetables, lettuce, parmesan, herb dressing, pickled onions",
    },
    price: 12,
    image: PHOTOS.salotos,
    category: "food",
    section: "salads",
    allergens: ["shellfish"],
  },
  // —— Pagrindiniai ——
  {
    id: "bulviniai-lasisa",
    name: { lt: "Bulviniai blynai su lašiša ir žolelių varške", en: "Potato pancakes with salmon & herb cheese" },
    description: {
      lt: "Tarkuotų bulvių blynai su rūkyta lašiša ir trinta varške su žolelėmis",
      en: "Grated potato pancakes with smoked salmon and herb cream cheese",
    },
    price: 12,
    image: PHOTOS.salotos,
    category: "food",
    section: "mains",
    allergens: ["fish", "dairy"],
  },
  {
    id: "wok-vistiena",
    name: { lt: "Azijietiški WOK makaronai su vištiena", en: "Asian WOK noodles with chicken" },
    description: {
      lt: "Ramen makaronai su daržovėmis teriyaki ir kario padaže",
      en: "Ramen noodles with vegetables in teriyaki and curry sauce",
    },
    price: 12,
    image: PHOTOS.makaronai,
    category: "food",
    section: "mains",
  },
  {
    id: "wok-krevetes",
    name: { lt: "Azijietiški WOK makaronai su krevetėmis", en: "Asian WOK noodles with shrimp" },
    description: {
      lt: "Ramen makaronai su daržovėmis teriyaki ir kario padaže",
      en: "Ramen noodles with vegetables in teriyaki and curry sauce",
    },
    price: 14,
    image: PHOTOS.makaronai,
    category: "food",
    section: "mains",
    allergens: ["shellfish"],
  },
  {
    id: "doner-lekste",
    name: { lt: "Libanietiško stiliaus vištienos Doner kebabas lėkštėje", en: "Lebanese chicken doner plate" },
    description: {
      lt: "Su bulvytėmis, „Coleslaw“ ir tabulės salotomis su kuskusu, marinuota paprika ir svogūnais bei pitos duonele",
      en: "With fries, coleslaw and tabbouleh with couscous, marinated paprika, onions and pita bread",
    },
    price: 14,
    image: PHOTOS.tortilija,
    category: "food",
    section: "mains",
  },
  {
    id: "bbq-sparneliai",
    name: { lt: "BBQ vištienos sparneliai", en: "BBQ chicken wings" },
    description: {
      lt: "BBQ sweet chilli vištienos sparneliai su kopūstų-agurkų salotomis ir bulvių skiltelėmis",
      en: "BBQ sweet chilli wings with coleslaw and potato wedges",
    },
    price: 14,
    image: PHOTOS.sparneliai,
    category: "food",
    section: "mains",
  },
  {
    id: "sumustiniai",
    name: { lt: "Trikampiai sumuštiniai su bulvytėmis", en: "Triangle sandwiches with fries" },
    description: {
      lt: "Kepti sumuštiniai su trijų rūšių sūriais, vištiena, pomidorais, marinuotų agurkų-garstyčių padažu, adžika ir marinuotais svogūnais",
      en: "Grilled sandwiches with three cheeses, chicken, tomato, pickle-mustard sauce, adjika and pickled onions",
    },
    price: 14,
    image: PHOTOS.baras3,
    category: "food",
    section: "mains",
  },
  {
    id: "pita-jautiena",
    name: { lt: "Kepta itališka pita su jautiena ir bulvytėmis", en: "Grilled Italian pita with beef & fries" },
    description: {
      lt: "Kepta įdaryta pita su malta jautiena, mocarelos sūriu, pomidorais, mėsainių padažu ir bulvytėmis su raudonėliu",
      en: "Grilled stuffed pita with ground beef, mozzarella, tomatoes, burger sauce and fries with oregano",
    },
    price: 13,
    image: PHOTOS.tortilija,
    category: "food",
    section: "mains",
  },
  {
    id: "zemaiciu-blynai",
    name: { lt: "Žemaičių blynai", en: "Samogitian pancakes" },
    description: {
      lt: "Patiekiami su ciberžoliniu grietinės ir sviesto padažu bei žolelėmis",
      en: "Served with turmeric sour cream and butter sauce with herbs",
    },
    price: 10,
    image: PHOTOS.baras5,
    category: "food",
    section: "mains",
  },
  {
    id: "cepelinai",
    name: { lt: "Cepelinai su mėsa", en: "Cepelinai with meat" },
    description: {
      lt: "Patiekiami su grietine ir spirgučiais",
      en: "Served with sour cream and cracklings",
    },
    price: 10,
    image: PHOTOS.baras4,
    category: "food",
    section: "mains",
  },
  {
    id: "vistienos-juosteles",
    name: { lt: "Traškios vištienos juostelės su bulvytėmis ir padažu", en: "Crispy chicken strips with fries" },
    description: { lt: "Vištienos juostelės traškioje plutelėje su bulvytėmis ir padažu", en: "Chicken strips in crispy coating with fries and sauce" },
    price: 9,
    image: PHOTOS.sparneliai,
    category: "food",
    section: "mains",
  },
  {
    id: "varsketukai",
    name: { lt: "Kepti varškėčiai", en: "Fried curd pancakes" },
    description: {
      lt: "Patiekiami su uogiene ir grietine arba karamele",
      en: "Served with jam and sour cream or caramel",
    },
    price: 9,
    image: PHOTOS.baras,
    category: "food",
    section: "mains",
  },
  // —— Sriubos ——
  {
    id: "sriuba-lasisa",
    name: { lt: "Azijietiška sriuba su lašiša", en: "Asian soup with salmon" },
    description: {
      lt: "Azijietiška sriuba su kokosų pienu, lašiša, daržovėmis ir ramen makaronais",
      en: "Asian soup with coconut milk, salmon, vegetables and ramen noodles",
    },
    price: 9,
    image: PHOTOS.makaronai,
    category: "food",
    section: "soups",
    allergens: ["fish"],
  },
  {
    id: "saltibarsciai",
    name: { lt: "Šaltibarščiai", en: "Cold beetroot soup" },
    description: { lt: "Tradiciniai lietuviški šaltibarščiai", en: "Traditional Lithuanian cold beetroot soup" },
    price: 6,
    image: PHOTOS.saltibarsciai,
    category: "food",
    section: "soups",
    vegan: true,
  },
  // —— Desertai ——
  {
    id: "churros",
    name: { lt: "Ispaniškos churros", en: "Spanish churros" },
    description: {
      lt: "Patiekiamos su kakaviniu kondensuoto pieno padažu",
      en: "Served with cocoa condensed milk sauce",
    },
    price: 6,
    image: PHOTOS.baras2,
    category: "food",
    section: "desserts",
  },
  {
    id: "obuoliu-pyragas",
    name: { lt: "Obuolių pyragas", en: "Apple pie" },
    description: {
      lt: "Šiltas obuolių pyragas su vaniliniais ledais ir karamele",
      en: "Warm apple pie with vanilla ice cream and caramel",
    },
    price: 6,
    image: PHOTOS.baras3,
    category: "food",
    section: "desserts",
  },
  {
    id: "vaniliniai-ledai",
    name: { lt: "Vaniliniai ledai su karamele", en: "Vanilla ice cream with caramel" },
    description: { lt: "Vaniliniai ledai su karamele", en: "Vanilla ice cream with caramel" },
    price: 5,
    image: PHOTOS.baras4,
    category: "food",
    section: "desserts",
  },
  // —— Pilstomas alus ——
  {
    id: "estrella-damm",
    name: { lt: "Estrella Damm", en: "Estrella Damm" },
    description: { lt: "Ispaniškas šviesus alus", en: "Spanish light lager" },
    price: 5,
    image: PHOTOS.baras2,
    category: "wineBeer",
    section: "beerDraft",
  },
  {
    id: "super-8",
    name: { lt: "Super 8", en: "Super 8" },
    description: { lt: "Nefiltruotas kvietinis blanche", en: "Unfiltered wheat blanche" },
    price: 5,
    image: PHOTOS.baras2,
    category: "wineBeer",
    section: "beerDraft",
  },
  {
    id: "czech-inn",
    name: { lt: "Czech Inn", en: "Czech Inn" },
    description: { lt: "Čekiškas tamsus alus", en: "Czech dark lager" },
    price: 5,
    image: PHOTOS.baras2,
    category: "wineBeer",
    section: "beerDraft",
  },
  {
    id: "complot-ipa",
    name: { lt: "Complot IPA", en: "Complot IPA" },
    description: { lt: "IPA alus", en: "IPA beer" },
    price: 5,
    image: PHOTOS.baras2,
    category: "wineBeer",
    section: "beerDraft",
  },
  // —— Alus buteliuose ——
  {
    id: "dundulio-cyrulis",
    name: { lt: "Dundulio Cyrulis", en: "Dundulis Cyrulis" },
    description: { lt: "Pilsneris", en: "Pilsner" },
    price: 5,
    image: PHOTOS.baras3,
    category: "wineBeer",
    section: "beerBottle",
  },
  {
    id: "dundulio-debesainis",
    name: { lt: "Dundulio Debesainis", en: "Dundulis Debesainis" },
    description: { lt: "Kvietinis alus", en: "Wheat beer" },
    price: 5,
    image: PHOTOS.baras3,
    category: "wineBeer",
    section: "beerBottle",
  },
  {
    id: "dundulio-simkala",
    name: { lt: "Dundulio Simkala APA", en: "Dundulis Simkala APA" },
    description: { lt: "Amerikietiškas pale ale", en: "American pale ale" },
    price: 5,
    image: PHOTOS.baras3,
    category: "wineBeer",
    section: "beerBottle",
  },
  {
    id: "dundulio-nealkoholinis",
    name: { lt: "Dundulio nealkoholinis alus", en: "Dundulis non-alcoholic beer" },
    description: { lt: "Nealkoholinis alus", en: "Non-alcoholic beer" },
    price: 5,
    image: PHOTOS.baras3,
    category: "wineBeer",
    section: "beerBottle",
  },
  {
    id: "alus-sveciias",
    name: { lt: "Alus svečias", en: "Guest beer" },
    description: { lt: "Rotuojamas alaus pasirinkimas", en: "Rotating guest beer selection" },
    price: 5,
    image: PHOTOS.baras3,
    category: "wineBeer",
    section: "beerBottle",
  },
  // —— Stiprieji ——
  {
    id: "romas-plantation-3",
    name: { lt: "Plantation 3 Stars Artisanal", en: "Plantation 3 Stars Artisanal" },
    description: { lt: "Romas 40 ml", en: "Rum 40 ml" },
    price: 6,
    image: PHOTOS.baras4,
    category: "wineBeer",
    section: "spirits",
  },
  {
    id: "romas-fiji",
    name: { lt: "Plantation Isle of Fiji", en: "Plantation Isle of Fiji" },
    description: { lt: "Romas 40 ml", en: "Rum 40 ml" },
    price: 6,
    image: PHOTOS.baras4,
    category: "wineBeer",
    section: "spirits",
  },
  {
    id: "romas-canerock",
    name: { lt: "Canerock", en: "Canerock" },
    description: { lt: "Romas 40 ml", en: "Rum 40 ml" },
    price: 6,
    image: PHOTOS.baras4,
    category: "wineBeer",
    section: "spirits",
  },
  {
    id: "viskis-black-ram",
    name: { lt: "Black Ram", en: "Black Ram" },
    description: { lt: "Viskis 40 ml", en: "Whiskey 40 ml" },
    price: 5,
    image: PHOTOS.baras4,
    category: "wineBeer",
    section: "spirits",
  },
  {
    id: "viskis-jack",
    name: { lt: "Jack Daniel's", en: "Jack Daniel's" },
    description: { lt: "Viskis 40 ml", en: "Whiskey 40 ml" },
    price: 6,
    image: PHOTOS.baras4,
    category: "wineBeer",
    section: "spirits",
  },
  {
    id: "viskis-haig",
    name: { lt: "Haig Club", en: "Haig Club" },
    description: { lt: "Viskis 40 ml", en: "Whiskey 40 ml" },
    price: 6,
    image: PHOTOS.baras4,
    category: "wineBeer",
    section: "spirits",
  },
  {
    id: "viskis-jameson",
    name: { lt: "Jameson", en: "Jameson" },
    description: { lt: "Viskis 40 ml", en: "Whiskey 40 ml" },
    price: 6,
    image: PHOTOS.baras4,
    category: "wineBeer",
    section: "spirits",
  },
  {
    id: "viskis-kaiji",
    name: { lt: "Kaiji", en: "Kaiji" },
    description: { lt: "Viskis 40 ml (Japonija)", en: "Whiskey 40 ml (Japan)" },
    price: 7,
    image: PHOTOS.baras4,
    category: "wineBeer",
    section: "spirits",
  },
  {
    id: "tequila-olmeca",
    name: { lt: "Olmeca Silver", en: "Olmeca Silver" },
    description: { lt: "Tekila 40 ml", en: "Tequila 40 ml" },
    price: 6,
    image: PHOTOS.baras4,
    category: "wineBeer",
    section: "spirits",
  },
  {
    id: "likeris-jager",
    name: { lt: "Jägermeister", en: "Jägermeister" },
    description: { lt: "Likeris 40 ml", en: "Liqueur 40 ml" },
    price: 5,
    image: PHOTOS.baras4,
    category: "wineBeer",
    section: "spirits",
  },
  {
    id: "likeris-amarula",
    name: { lt: "Amarula grietinėlės likeris", en: "Amarula cream liqueur" },
    description: { lt: "Likeris 40 ml", en: "Liqueur 40 ml" },
    price: 5,
    image: PHOTOS.baras4,
    category: "wineBeer",
    section: "spirits",
  },
  {
    id: "likeris-sambuca",
    name: { lt: "Sambuca", en: "Sambuca" },
    description: { lt: "Likeris 40 ml", en: "Liqueur 40 ml" },
    price: 5,
    image: PHOTOS.baras4,
    category: "wineBeer",
    section: "spirits",
  },
  {
    id: "degtine-gustav",
    name: { lt: "Gustav Arctic", en: "Gustav Arctic" },
    description: { lt: "Degtinė 40 ml", en: "Vodka 40 ml" },
    price: 5,
    image: PHOTOS.baras4,
    category: "wineBeer",
    section: "spirits",
  },
  {
    id: "degtine-samane",
    name: { lt: "Dzūkiška samanė", en: "Dzūkiška samanė" },
    description: { lt: "Degtinė 40 ml su vieno kąsnio užkandėle", en: "Vodka 40 ml with a bite-size snack" },
    price: 6,
    image: PHOTOS.baras4,
    category: "wineBeer",
    section: "spirits",
  },
  {
    id: "brendis-askaneli",
    name: { lt: "Askaneli", en: "Askaneli" },
    description: { lt: "Brendis 40 ml", en: "Brandy 40 ml" },
    price: 5,
    image: PHOTOS.baras4,
    category: "wineBeer",
    section: "spirits",
  },
  // —— Vynas ——
  {
    id: "vynas-primitivo",
    name: { lt: "Primitivo", en: "Primitivo" },
    description: { lt: "Raudonas sausas vynas 150 ml", en: "Dry red wine 150 ml" },
    price: 5,
    image: PHOTOS.baras5,
    category: "wineBeer",
    section: "wine",
  },
  {
    id: "vynas-riesling",
    name: { lt: "Riesling", en: "Riesling" },
    description: { lt: "Pusiau saldus vynas 150 ml", en: "Semi-sweet wine 150 ml" },
    price: 5,
    image: PHOTOS.baras5,
    category: "wineBeer",
    section: "wine",
  },
  {
    id: "vynas-pinot",
    name: { lt: "Pinot Grigio", en: "Pinot Grigio" },
    description: { lt: "Baltas sausas vynas 150 ml", en: "Dry white wine 150 ml" },
    price: 5,
    image: PHOTOS.baras5,
    category: "wineBeer",
    section: "wine",
  },
  {
    id: "karstas-vynas",
    name: { lt: "Karštas vynas", en: "Mulled wine" },
    description: { lt: "Karštas vynas", en: "Mulled wine" },
    price: 6,
    image: PHOTOS.baras5,
    category: "wineBeer",
    section: "wine",
  },
  {
    id: "sangria",
    name: { lt: "Sangria 1 l", en: "Sangria 1 l" },
    description: { lt: "Sangria 1 litras", en: "Sangria 1 litre" },
    price: 15,
    image: PHOTOS.baras5,
    category: "wineBeer",
    section: "wine",
  },
  // —— Sidras ——
  {
    id: "sidras-tinginio",
    name: { lt: "Tinginio Pantis obuolių sidras 0,33 l", en: "Tinginio Pantis apple cider 0.33 l" },
    description: { lt: "Obuolių sidras", en: "Apple cider" },
    price: 5,
    image: PHOTOS.baras3,
    category: "wineBeer",
    section: "cider",
  },
  // —— Kokteiliai ——
  {
    id: "cuba-libre",
    name: { lt: "Cuba Libre", en: "Cuba Libre" },
    description: { lt: "Alkoholinis kokteilis", en: "Alcoholic cocktail" },
    price: 10,
    image: PHOTOS.baras2,
    category: "cocktails",
    section: "cocktails",
  },
  {
    id: "negroni",
    name: { lt: "Negroni", en: "Negroni" },
    description: { lt: "Alkoholinis kokteilis", en: "Alcoholic cocktail" },
    price: 10,
    image: PHOTOS.baras2,
    category: "cocktails",
    section: "cocktails",
  },
  {
    id: "viskio-obuoliu",
    name: { lt: "Viskio ir obuolių kokteilis", en: "Whiskey & apple cocktail" },
    description: { lt: "Alkoholinis kokteilis", en: "Alcoholic cocktail" },
    price: 10,
    image: PHOTOS.baras2,
    category: "cocktails",
    section: "cocktails",
  },
  {
    id: "pasifloru",
    name: { lt: "Pasiflorų kokteilis", en: "Passion fruit cocktail" },
    description: { lt: "Alkoholinis kokteilis", en: "Alcoholic cocktail" },
    price: 11,
    image: PHOTOS.baras2,
    category: "cocktails",
    section: "cocktails",
  },
  {
    id: "aperol-spritz",
    name: { lt: "Aperol Spritz", en: "Aperol Spritz" },
    description: { lt: "Alkoholinis kokteilis", en: "Alcoholic cocktail" },
    price: 11,
    image: PHOTOS.baras2,
    category: "cocktails",
    section: "cocktails",
  },
  {
    id: "aperol-arbuzinis",
    name: { lt: "Aperol arbūzinis", en: "Watermelon Aperol" },
    description: { lt: "Alkoholinis kokteilis", en: "Alcoholic cocktail" },
    price: 11,
    image: PHOTOS.baras2,
    category: "cocktails",
    section: "cocktails",
  },
  {
    id: "green-banana",
    name: { lt: "Green Banana", en: "Green Banana" },
    description: { lt: "Alkoholinis kokteilis", en: "Alcoholic cocktail" },
    price: 11,
    image: PHOTOS.baras2,
    category: "cocktails",
    section: "cocktails",
  },
  {
    id: "mango-gin-tonic",
    name: { lt: "Mango Gin Tonic", en: "Mango Gin & Tonic" },
    description: { lt: "Alkoholinis kokteilis", en: "Alcoholic cocktail" },
    price: 11,
    image: PHOTOS.baras2,
    category: "cocktails",
    section: "cocktails",
  },
  {
    id: "avietine-lambada",
    name: { lt: "Avietinė Lambada", en: "Raspberry Lambada" },
    description: { lt: "Alkoholinis kokteilis", en: "Alcoholic cocktail" },
    price: 11,
    image: PHOTOS.baras2,
    category: "cocktails",
    section: "cocktails",
  },
  {
    id: "kiwi-cucumber",
    name: { lt: "Kiwi Cucumber", en: "Kiwi Cucumber" },
    description: { lt: "Alkoholinis kokteilis", en: "Alcoholic cocktail" },
    price: 12,
    image: PHOTOS.baras2,
    category: "cocktails",
    section: "cocktails",
  },
  {
    id: "kefyro-special",
    name: { lt: "Kefyro ūsų special", en: "Kefyro ūsai special" },
    description: { lt: "Firminis baro kokteilis", en: "Signature bar cocktail" },
    price: 13,
    image: PHOTOS.baras2,
    category: "cocktails",
    section: "cocktails",
  },
  // —— Shotai ——
  {
    id: "shot-viskio-cinamono",
    name: { lt: "Viskio cinamono shotai", en: "Cinnamon whiskey shots" },
    description: { lt: "4 vnt.", en: "4 pcs" },
    price: 12,
    image: PHOTOS.baras3,
    category: "cocktails",
    section: "shots",
  },
  {
    id: "shot-braske",
    name: { lt: "Braškių shotai", en: "Strawberry shots" },
    description: { lt: "4 vnt.", en: "4 pcs" },
    price: 14,
    image: PHOTOS.baras3,
    category: "cocktails",
    section: "shots",
  },
  {
    id: "shot-laimo-pasifloru",
    name: { lt: "Laimo-pasiflorų shotai", en: "Lime & passion fruit shots" },
    description: { lt: "4 vnt.", en: "4 pcs" },
    price: 14,
    image: PHOTOS.baras3,
    category: "cocktails",
    section: "shots",
  },
  {
    id: "shot-kefyro",
    name: { lt: "Kefyro ūsų shotai", en: "Kefyro ūsai shots" },
    description: { lt: "4 vnt.", en: "4 pcs" },
    price: 14,
    image: PHOTOS.baras3,
    category: "cocktails",
    section: "shots",
  },
  // —— Kava ——
  {
    id: "kava-espresso",
    name: { lt: "Juoda kava / Espresso", en: "Black coffee / Espresso" },
    description: { lt: "Karšta kava", en: "Hot coffee" },
    price: 2,
    image: PHOTOS.baras,
    category: "nonAlcoholic",
    section: "coffee",
  },
  {
    id: "kava-cappuccino",
    name: { lt: "Cappuccino / Latte", en: "Cappuccino / Latte" },
    description: { lt: "Karšta kava", en: "Hot coffee" },
    price: 3,
    image: PHOTOS.baras,
    category: "nonAlcoholic",
    section: "coffee",
  },
  {
    id: "kava-salta",
    name: { lt: "Šalta kava", en: "Iced coffee" },
    description: { lt: "Šaltas kavos gėrimas", en: "Cold coffee drink" },
    price: 5,
    image: PHOTOS.baras,
    category: "nonAlcoholic",
    section: "coffee",
  },
  {
    id: "kakava",
    name: { lt: "Kakava", en: "Hot chocolate" },
    description: { lt: "Karšta kakava", en: "Hot chocolate" },
    price: 4,
    image: PHOTOS.baras,
    category: "nonAlcoholic",
    section: "coffee",
  },
  {
    id: "arbata",
    name: { lt: "Arbata", en: "Tea" },
    description: {
      lt: "Žolelių / juodoji su cinamonu / mėtų",
      en: "Herbal / black with cinnamon / mint",
    },
    price: 3,
    image: PHOTOS.baras,
    category: "nonAlcoholic",
    section: "coffee",
  },
  // —— Nealkoholiniai ——
  {
    id: "on-lemon",
    name: { lt: "On Lemon limonadas", en: "On Lemon lemonade" },
    description: {
      lt: "Rabarbarų, juodųjų serbentų, apelsinų arba kriaušių",
      en: "Rhubarb, blackcurrant, orange or pear",
    },
    price: 4,
    image: PHOTOS.baras5,
    category: "nonAlcoholic",
    section: "soft",
    vegan: true,
  },
  {
    id: "kefyro-limonadas",
    name: { lt: "Kefyro ūsų limonadas 1 l", en: "Kefyro ūsai lemonade 1 l" },
    description: { lt: "Pasiflorų arba obuolių", en: "Passion fruit or apple" },
    price: 8,
    image: PHOTOS.baras5,
    category: "nonAlcoholic",
    section: "soft",
    vegan: true,
  },
  {
    id: "gira",
    name: { lt: "Gira", en: "Kvass" },
    description: { lt: "Tradicinė ruginė gira", en: "Traditional rye kvass" },
    price: 3,
    image: PHOTOS.baras5,
    category: "nonAlcoholic",
    section: "soft",
    vegan: true,
  },
  {
    id: "kombucha",
    name: { lt: "Kombučia", en: "Kombucha" },
    description: { lt: "Fermentuota arbata", en: "Fermented tea" },
    price: 4,
    image: PHOTOS.baras5,
    category: "nonAlcoholic",
    section: "soft",
    vegan: true,
  },
  {
    id: "coca-cola",
    name: { lt: "Coca-Cola 0,2 l", en: "Coca-Cola 0.2 l" },
    description: { lt: "Coca-Cola", en: "Coca-Cola" },
    price: 3,
    image: PHOTOS.baras5,
    category: "nonAlcoholic",
    section: "soft",
  },
  {
    id: "vanduo",
    name: { lt: "Mineralinis vanduo", en: "Mineral water" },
    description: { lt: "0,33 l arba 0,75 l", en: "0.33 l or 0.75 l" },
    price: 3,
    displayPrice: { lt: "3 / 4 €", en: "€3 / €4" },
    image: PHOTOS.baras5,
    category: "nonAlcoholic",
    section: "soft",
    vegan: true,
  },
  {
    id: "pieno-ledu-kokteilis",
    name: { lt: "Pieno ir ledų kokteilis", en: "Milk & ice cream shake" },
    description: { lt: "Pieno ir ledų kokteilis", en: "Milk and ice cream shake" },
    price: 5,
    image: PHOTOS.baras5,
    category: "nonAlcoholic",
    section: "soft",
  },
  {
    id: "aperol-nealkoholinis",
    name: { lt: "Nealkoholinis Aperol Spritz", en: "Non-alcoholic Aperol Spritz" },
    description: { lt: "Bealkoholinis kokteilis", en: "Non-alcoholic cocktail" },
    price: 8,
    image: PHOTOS.baras2,
    category: "nonAlcoholic",
    section: "soft",
    vegan: true,
  },
];

function menuItem(id: string): ScrapedMenuItem {
  const item = SCRAPED_MENU.find((i) => i.id === id);
  if (!item) throw new Error(`Missing menu item: ${id}`);
  return item;
}

export const FEATURED_ITEMS: ScrapedMenuItem[] = [
  menuItem("tortilija-vistiena"),
  menuItem("doner-lekste"),
  menuItem("bbq-sparneliai"),
  menuItem("mango-gin-tonic"),
  menuItem("aperol-spritz"),
  menuItem("kefyro-special"),
  menuItem("salotos-krevetes"),
  menuItem("churros"),
  menuItem("saltibarsciai"),
  menuItem("wok-krevetes"),
];

export const DAILY_SPECIALS_SCRAPED: ScrapedMenuItem[] = [
  menuItem("doner-lekste"),
  menuItem("bbq-sparneliai"),
  menuItem("sriuba-lasisa"),
];
